# Cargo config file. 
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="manta_api=debug"

# -- Service Environment Variables
# IMPORTANT: 
#   For cargo commands only.
#   For deployed env, should be managed by container 
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

SERVICE_DB_URL="postgres://app_user:dev_only_password@localhost/app_db"

SERVICE_PASSWORD_KEY="U96vOyRaI4tjumjHRk0FK2D1N1UAg2jiVZ66y-3Q0k_BfgY3Gmvft0A2JDzb9ZgT2QzGPgBUJnGtc_1MBeUS5w"

SERVICE_TOKEN_KEY="CUF2rzJgVUSMYKls9ysmUGbZlha7H-HvqjHroY_wYPuUZsXqz7wpkGn3XVubVY8wfhLH7H8_0ksxOMkJiSiCWQ"
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minutes

## -- ConfigMap

# This will be relative to Cargo.toml.
# In prod dockers, probably use absolute path.
SERVICE_WEB_FOLDER="web-folder/" 
